---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  namespace: ambassador
spec:
  type: LoadBalancer
  loadBalancerIP: '__LOAD_BALANCER_IP__'
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
  selector:
    service: ambassador
